#!/bin/bash

# Local to PR Automation Script
# Creates focused PRs for BugBot systematic review

if [ $# -lt 2 ]; then
    echo "Usage: $0 <PR_TITLE> <PR_DESCRIPTION> [SOURCE_BRANCH]"
    echo "Example: $0 'Core App Components Review' 'BugBot scan of main app entry point'"
    exit 1
fi

PR_TITLE="$1"
PR_DESCRIPTION="$2"
SOURCE_BRANCH="${3:-bugbot-review-$(date +%s)}"

echo "🚀 Creating BugBot Review PR"
echo "============================"
echo "Title: $PR_TITLE"
echo "Description: $PR_DESCRIPTION"
echo "Source Branch: $SOURCE_BRANCH"
echo ""

# Check if we're in a git repository
if [ ! -d ".git" ]; then
    echo "❌ Not in a git repository. Please run from project root."
    exit 1
fi

# Check if GitHub CLI is available
if ! command -v gh &> /dev/null; then
    echo "❌ GitHub CLI not found. Please install: winget install GitHub.cli"
    exit 1
fi

# Check authentication
if ! gh auth status &> /dev/null; then
    echo "❌ Not authenticated with GitHub. Please run: gh auth login"
    exit 1
fi

echo "✅ Prerequisites check passed"
echo ""

# Create and switch to new branch
echo "🌿 Creating branch: $SOURCE_BRANCH"
git checkout -b "$SOURCE_BRANCH"

# Create a minimal change to trigger BugBot
echo "📝 Creating BugBot trigger file"
cat > "BUG_BOT_TRIGGER.md" << EOF
# BugBot Review Trigger

**PR Title:** $PR_TITLE
**Description:** $PR_DESCRIPTION
**Created:** $(date -u)
**Branch:** $SOURCE_BRANCH

## Files to Review
This PR is designed to trigger BugBot analysis of the following components:

- Core application files
- UI components and views
- Pipeline modules
- Services and integrations
- Data persistence layer

## BugBot Analysis Request
Please perform comprehensive analysis of:
1. Code quality and best practices
2. Security vulnerabilities
3. Performance optimizations
4. Architecture improvements
5. Bug detection and fixes

## Automation Status
- [x] PR created via automation
- [x] BugBot trigger file created
- [ ] BugBot analysis in progress
- [ ] Results reviewed
- [ ] Fixes applied

---
*This file was automatically generated by the strategic PR automation system.*
EOF

# Add and commit changes
git add BUG_BOT_TRIGGER.md
git commit -m "BugBot Review: $PR_TITLE

$PR_DESCRIPTION

Automated PR creation for systematic codebase review.
BugBot trigger file created for analysis."

# Push branch
echo "📤 Pushing branch to GitHub"
git push origin "$SOURCE_BRANCH"

# Create PR using GitHub CLI
echo "🔗 Creating Pull Request"
PR_URL=$(gh pr create \
    --title "BugBot Review: $PR_TITLE" \
    --body "$PR_DESCRIPTION

## BugBot Analysis Request

This PR is created as part of a systematic review of the DirectorStudio codebase.

### Analysis Scope
- Code quality and best practices
- Security vulnerabilities  
- Performance optimizations
- Architecture improvements
- Bug detection and fixes

### Files Included
This PR focuses on the components specified in the title for targeted analysis.

### Automation
- Created via strategic PR automation
- BugBot trigger file included
- Part of systematic codebase review

### Next Steps
1. BugBot will analyze the code
2. Issues and improvements will be identified
3. Fixes will be applied as needed
4. Results will be documented

---
*Created by DirectorStudio Strategic PR Automation*" \
    --label "bugbot-review,automation,systematic-review" \
    --assignee "@me")

if [ $? -eq 0 ]; then
    echo "✅ PR created successfully!"
    echo "🔗 URL: $PR_URL"
    
    # Extract PR number
    PR_NUMBER=$(echo "$PR_URL" | grep -o '[0-9]\+' | tail -1)
    
    echo ""
    echo "📊 PR Details:"
    echo "- Number: #$PR_NUMBER"
    echo "- Title: BugBot Review: $PR_TITLE"
    echo "- Branch: $SOURCE_BRANCH"
    echo "- URL: $PR_URL"
    
    # Update local status
    echo ""
    echo "📝 Updating local status files..."
    
    # Update PR_LIVE_STATUS.md
    cat > PR_LIVE_STATUS.md << EOF
# Live PR Status - BugBot Review

## 🤖 **Current BugBot Review PR**

**PR Number:** #$PR_NUMBER  
**Title:** BugBot Review: $PR_TITLE  
**Description:** $PR_DESCRIPTION  
**Branch:** $SOURCE_BRANCH  
**URL:** $PR_URL  
**Status:** Created  
**Created:** $(date -u)  

## 🔍 **BugBot Analysis Request**

This PR is designed to trigger BugBot analysis of DirectorStudio components.

### Analysis Scope:
- Code quality and best practices
- Security vulnerabilities
- Performance optimizations
- Architecture improvements
- Bug detection and fixes

### Files Focus:
$PR_TITLE

## 📋 **Status Tracking**

- [x] PR created via automation
- [x] BugBot trigger file created
- [x] Branch pushed to GitHub
- [x] PR created with labels
- [ ] BugBot analysis in progress
- [ ] Results reviewed
- [ ] Fixes applied

## 🔄 **Next Steps**

1. BugBot will analyze the code
2. Issues and improvements identified
3. Fixes applied as needed
4. Results documented

---
*Updated by DirectorStudio Strategic PR Automation*
EOF

    echo "✅ Local status updated"
    
else
    echo "❌ Failed to create PR"
    exit 1
fi

# Return to main branch
git checkout main

echo ""
echo "🎉 BugBot Review PR Created Successfully!"
echo "=========================================="
echo "PR #$PR_NUMBER: BugBot Review: $PR_TITLE"
echo "URL: $PR_URL"
echo ""
echo "📋 Next Steps:"
echo "1. BugBot will analyze the code automatically"
echo "2. Monitor progress at: $PR_URL"
echo "3. Review findings and apply fixes"
echo "4. Continue with next PR in the strategic plan"
echo ""
