name: Auto Merge PRs

on:
  pull_request:
    types: [opened, labeled]

jobs:
  enable-auto-merge:
    if: contains(github.event.pull_request.labels.*.name, 'automated')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Enable Auto-Merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
